- terraform/main.tf
- terraform/variables.tf
> AEA-191: Update terraform files to match the PDS repo.

- proxies/live/apiproxy/proxies/default.xml
- proxies/sandbox/apiproxy/proxies/default.xml
- specification/electronic-prescriptions.yaml
> Improve sandbox overview

- Makefile
- package.json
- scripts/set_spec_server_dev.sh
- specification/electronic-prescription-service-api.yaml
> AEA-250 Deploy spec to internal portal

- Makefile
- azure-pipelines.yml
- scripts/build_proxy.sh
> Aea 250 deploy spec to internal portal

- Makefile
- README.md
- sandbox/tests/request-validator.spec.js
- sandbox/tests/resources/valid-bundle-with-signature.json
- sandbox/tests/resources/valid-bundle.json
- sandbox/tests/services/request-body-parser.spec.js
- sandbox/tests/validators/request-validator.spec.js
- sandbox/validators/request-validator.js
> Added extra snapshot tests for validator

- README.md
> Update readme to remove sandbox app references

- specification/electronic-prescription-service-api.yaml
> Update specification wording

- README.md
- azure-pipelines.yml
> AEA-374 Api code improvements

- azure-pipelines.yml
Update draft github release to include repository assets
> Update draft github release to include repository assets

- specification/electronic-prescription-service-api.yaml
> Documentation changes for consistency with PDS

- tests/e2e/pact/resources/example-1-repeat-dispensing/SendRequest-FhirMessageSigned.json
- tests/e2e/pact/specs/eps-sandbox.spec.ts
- tests/e2e/pact/specs/eps.spec.ts
> created symlink for send request, used in send endpoint pact test

- azure-pipelines.yml
- coordinator/src/model/fhir-resources.ts
- coordinator/src/routes/prescription/post-send-message.ts
- coordinator/src/services/translation/common.ts
- coordinator/tests/services/translation/common.spec.ts
- models/examples/example-1-repeat-dispensing/SendRequest-SuccessResponse.json
- models/schemas/OperationOutcome-2XX.yaml
- scripts/update_coordinator_tests.py
- specification/electronic-prescription-service-api.yaml
- tests/e2e/pact/specs/eps.spec.ts
> Aea 423 spine responses into operationoutcome

- models/examples/example-1-repeat-dispensing/PrepareRequest-FhirMessageUnsigned.json
- models/examples/example-1-repeat-dispensing/SendRequest-FhirMessageSigned.json
- models/examples/example-2-acute-nominated-pharmacy/PrepareRequest-FhirMessageUnsigned.json
- models/examples/example-2-acute-nominated-pharmacy/SendRequest-FhirMessageSigned.json
- models/examples/example-b-spine-error-patient-deceased/SendRequest-FhirMessageSigned.json
- models/schemas/Bundle.yaml
- models/schemas/Coding-MessageDefinition.yaml
- models/schemas/MedicationRequest.yaml
- models/schemas/MessageHeader.yaml
- models/schemas/OperationOutcome-4XX.yaml
- models/schemas/OperationOutcome-5XX-send.yaml
- models/schemas/OperationOutcome-5XX.yaml
- models/schemas/Organization.yaml
- models/schemas/Parameters.yaml
- models/schemas/Patient.yaml
- models/schemas/Practitioner.yaml
- models/schemas/PractitionerRole.yaml
- specification/electronic-prescription-service-api.yaml
> AEA-377: Add MessageHeader to specification

- .github/workflows/continuous-integration.yml
> APM-1316 Add github action wokflow to tag merges to master

- azure/azure-pr-pipeline.yml
- azure/azure-release-pipeline.yml
environments to release pipeline
> AEA-617 Add ref environment

- coordinator/src/services/handlers/spine-handler.ts
- proxies/live/apiproxy/proxies/default.xml
in internal-dev for pr pipeline validation
> AEA-617 Test connection to spine ref IG3 HL7 prescriptions

- coordinator/src/services/translation/cancellation/cancellation-response.ts
- coordinator/tests/services/translation/cancellation-response/cancellation-response.spec.ts
remove duplication of certain resources in fhir response from spine and update tests to reflect changes
> aea - remove bundle entry duplication

- coordinator/src/routes/debug/convert.ts
- coordinator/src/routes/dispense/release.ts
- coordinator/src/routes/dispense/task.ts
- coordinator/src/routes/prescribe/prepare.ts
- coordinator/src/routes/process.ts
- coordinator/src/routes/util.ts
make use of wrapper functions to handle user auth and external FHIR validator response
> make use of wrapper functions to handle user auth and external FHIR validator response

- coordinator/index.ts
- examples/secondary-care/community/acute/nominated-pharmacy/clinical-practitioner/controlled-drugs/2-Prepare-Request-200_OK.json
- examples/secondary-care/community/acute/nominated-pharmacy/health-professional/1-Prepare-Request-200_OK.json
- examples/secondary-care/community/acute/nominated-pharmacy/health-professional/1-Process-Request-Send-200_OK.json
- examples/secondary-care/community/acute/nominated-pharmacy/health-professional/6-Convert-Response-Send-200_OK.xml
- examples/secondary-care/community/acute/nominated-pharmacy/health-professional/6-Prepare-Request-200_OK.json
- examples/secondary-care/community/acute/nominated-pharmacy/health-professional/6-Process-Request-Send-200_OK.json
- examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/non-prescriber-endorsed/1-Convert-Response-Send-200_OK.xml
- examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/non-prescriber-endorsed/1-Process-Request-Send-200_OK.json
- examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/prescriber-endorsed/1-Convert-Response-Send-200_OK.xml
- examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/prescriber-endorsed/1-Process-Request-Send-200_OK.json
- examples/secondary-care/homecare/acute/nominated-pharmacy/clinical-practitioner/2-Prepare-Request-200_OK.json
- examples/secondary-care/homecare/acute/nominated-pharmacy/clinical-practitioner/2-Process-Request-Send-200_OK.json
- tests/e2e/pact/services/update-prescriptions.ts
Update prepare request ids to match prepare response ids before signing, check digest matches, fix non-matching digest examples
> ADO Signing Fixes

- coordinator/src/services/translation/response/organization.ts
- coordinator/tests/services/translation/response/organization.spec.ts
reflect in tests. also update org tests
> allow missing telecom fields in response translation

- coordinator/src/services/communication/sandbox-spine-client.ts
> Add patient release to sandbox

- azure/azure-release-pipeline.yml
- manifest_template.yml
- specification/electronic-prescription-service-api.yaml
> implement int preview

- specification/schemas/ErrorCode.yaml
**Description**
Remove readOnly label from response schemas.
More detail in: [ADZ-894](https://nhsd-jira.digital.nhs.uk/browse/ADZ-894)
> ADZ-894 Remove readOnly label from response schema

- poetry.lock
- pyproject.toml
https://github.com/NHSDigital/electronic-prescription-service-api/security/dependabot/pyproject.toml/requests/open﻿
> Address dependabot alert

- tool/azure/azure-build-pipeline.yml
- tool/docker-compose.yml
- tool/site/client-react/src/components/backButton.tsx
- tool/site/client-react/src/components/claim/claimForm.tsx
- tool/site/client-react/src/components/dispense/dispenseForm.tsx
- tool/site/client-react/src/components/longRunningTask.tsx
- tool/site/client-react/src/components/prescription-tracker/prescriptionSearchForm.tsx
- tool/site/client-react/src/components/prescriptionActions.tsx
- tool/site/client-react/src/components/reloadButton.tsx
- tool/site/client-react/src/pages/claimPage.tsx
- tool/site/client-react/src/pages/dispensePage.tsx
- tool/site/client-react/src/pages/sendPostSignPage.tsx
- tool/site/client-react/src/pages/sendPreSignPage.tsx
- tool/site/client-react/tests/components/__snapshots__/longRunningTask.spec.tsx.snap
- tool/site/client-react/tests/components/claim/__snapshots__/claimForm.spec.tsx.snap
- tool/site/client-react/tests/components/claim/claimForm.spec.tsx
- tool/site/client-react/tests/components/dispense/__snapshots__/dispenseForm.spec.tsx.snap
- tool/site/client-react/tests/components/longRunningTask.spec.tsx
- tool/site/client-react/tests/pages/__snapshots__/claimPage.spec.tsx.snap
- tool/site/client-react/tests/pages/__snapshots__/dispensePage.spec.tsx.snap
- tool/site/client-react/tests/pages/__snapshots__/prescriptionSearchPage.spec.tsx.snap
- tool/site/client-react/tests/pages/__snapshots__/sendPostSignPage.spec.tsx.snap
- tool/site/client-react/tests/pages/__snapshots__/sendPreSignPage.spec.tsx.snap
- tool/site/client/api/make-request.ts
- tool/site/client/data/prescriptions.ts
- tool/site/client/index.html
- tool/site/client/index.ts
- tool/site/client/ui/state.ts
- tool/site/client/ui/view-models.ts
- tool/site/server_flask/routes.py
* Every react result component now has a back button which reloads the form component which led to the result
* React form components which can be used multiple times now have a back button which goes back to previous page
* Too many requests response now captured when client is making requests to the backend
* Redirects are followed to oauth flow when access-token expires
* Load prescription examples are now deployed with epsat so they will be synced with deployed eps and epsat versions
* Remove code from client which has been migrated to react-client
> AEA-1730 Ensure consistent user journeys for EPSAT react pages

- specification/electronic-prescription-service-api.yaml
made it clear the APIs are user restricted
> Updated access mode in the OAS

- azure/azure-release-pipeline.yml
recommended params by platforms team
> edit pipeline permissions so everyone can release

- azure/azure-pr-pipeline.yml
https://nhsd-jira.digital.nhs.uk/browse/APM-2880
> APM-2880 Fix pipeline triggers

- tool/site/server_hapi/src/routes/dispense/release.ts
Add safety error handling to release response prescription with another dispenser
> Fix certain release failure scenarios in epsat

- tool/site/server_hapi/src/routes/dispense/dispense.ts
- tool/site/server_hapi/src/routes/dispense/release.ts
Transfer released prescription to release from sent, remove dispensed prescription from released
> Handle more prescription status changes in epsat my-prescriptions

- proxies/sandbox/apiproxy/policies/AssignMessage.AddCors.xml
I think I got this, though would appreciate a second pair of eyes.
> Included NHSD-Session-URID in Access-Control-Allow-Headers

- tool/site/server/src/config.ts
- tool/site/server/src/routes/auth/callback.ts
- tool/site/server/src/routes/auth/login.ts
- tool/site/server/src/services/session.ts
Clear session on login and clear logged-in cookie when refresh token expires
> AEA-2143 Fix EPSAT session clear

- coordinator/tests/services/verification/signature-verification.spec.ts
AEA-2754 Addition of tests for verify signature
> AEA-2754 Addition of tests for verify signature

- coordinator/package-lock.json
- coordinator/package.json
- coordinator/src/routes/dispense/verify-signature.ts
- coordinator/src/services/translation/common/dateTime.ts
- coordinator/src/services/translation/response/release/release-response.ts
- coordinator/src/services/verification/index.ts
- coordinator/src/services/verification/signature-verification.ts
- coordinator/tests/services/translation/common/dateTime.spec.ts
- coordinator/tests/services/verification/signature-verification.spec.ts
Checking the signature date is in range of the cert start and end date
> AEA-2647 verify at time of signature

- packages/coordinator/src/services/translation/response/spine-response-handler.ts
- packages/coordinator/src/services/translation/response/spine-return-handler.ts
- packages/coordinator/tests/services/translation/response/spine-response-handler.spec.ts
…eExtension containing org id, instead of ODS code.
> AEA-2661 Dispensing org within release rejection

- Makefile
- packages/coordinator/package-lock.json
- packages/e2e-tests/package-lock.json
- packages/tool/e2e-tests/package-lock.json
- packages/tool/site/server/package-lock.json
- Addressed vulnerabilities
- Added `make npm-audit-fix` command
> AEA-2644 Resolve some npm packages vulnerabilities

- .github/pull_request_template.md
- packages/tool/e2e-tests/helpers.ts
- Fixes login step in EPSAT E2E tests 
- Fixes login user for EPSAT E2E tests
- Add template for pull requests
> AEA-3551 fix EPSAT E2E tests

- .github/workflows/continuous-integration.yml
Brings release notes in line with other repos
> improve release notes message

- packages/specification/schemas/components/MedicationDispense/MedicationDispense.yaml
- packages/specification/schemas/components/MedicationRequest/CancelRequestMedicationRequest.yaml
- packages/specification/schemas/components/MedicationRequest/DispenseNotificationMedicationRequest.yaml
- packages/specification/schemas/components/MedicationRequest/MedicationRequest.yaml
- packages/specification/schemas/components/MedicationRequest/ReleaseMedicationRequest.yaml
- packages/specification/schemas/components/_extensions/DispensingMedicationRepeatInformation.yaml
- packages/specification/schemas/components/_fragments/dosageInstruction.yaml
- packages/specification/schemas/requests/dispensing/DispenseClaim.yaml
Updates appropriate fields in the OAS that were incorrect typed as integers to decimals. As swagger doesnt formally support the decimal type and the simplifier docs state that they should not be a float type they have been updated to a basic number type with a detailed description.
> [AEA-3500] Review and update incorrect integer fields

- .github/workflows/dependabot_auto_approve_and_merge.yml
Add workflow to auto approve and merge dependabot PR
> automerge and approve dependabot

- .github/workflows/dependabot_auto_approve_and_merge.yml
Use PAT for dependabot automerge
> use PAT for dependabot auto merge

- packages/specification/schemas/components/_fragments/groupIdentifier.yaml
- :exclamation: Breaking Change
- :sparkles: New Feature
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
> AEA-3269-Updated-to-include-newlines

- packages/specification/schemas/components/_fragments/groupIdentifier.yaml
- :exclamation: Breaking Change
- :sparkles: New Feature
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
> AEA-3269-Changed to bullet points from newlines

- .devcontainer/devcontainer.json
- Makefile
- packages/tool/docker-compose.yml
- packages/tool/site/Dockerfile
> run epsat locally

- .github/dependabot.yml
increase dependabot pull request limit
> update dependabot pull request limit

- Makefile
- fix makefile targets for release notes calls
> AEA-3662 fix makefile for release notes

- .github/workflows/create_int_release_notes.yml
- .github/workflows/create_prod_release_notes.yml
- .github/workflows/create_rc_int_release_notes.yml
- .github/workflows/mark_jira_released.yml
- use correct role for managing release notes
> fix releaase notes role

- .github/workflows/dependabot_auto_approve_and_merge.yml
- use github app for dependabot automerge
> use app for automerge

- packages/tool/e2e-tests/sandbox.test.ts
> fix headless tests for sandbox epsat

- scripts/calculate_version.py
- fix calculate version to look at whole message to work out changes
> fix calculate_version to look at whole message for commands

- azure/templates/pre_int_deploy.yml
- hard code tag when it is missing
> handle missing int tag

- azure/templates/pre_int_deploy.yml
- rollback previous change where version was hard coded
> rollback hard code version in pre_deploy int

- azure/templates/post_prod_deploy.yml
- fix getting tag post deployment as we are not in beta anymore
> fix getting tag post prod deploy as we are not in beta anymore

- package-lock.json
- packages/coordinator/package.json
- remove newman to resolve security issue
> remove newman to resolve security issue

- package-lock.json
- packages/tool/site/client/package.json
- packages/tool/site/server/package.json
- update sheetjs xlsx package to avoid security vulnerability
> update sheetjs xlsx package

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
- use latest validator version
> use latest validator version

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
- update validator to v1.0.158-alpha
> AEA-0000 update validator version

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
Updates validator version
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
> Updates validator version

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
Updating validator version
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
> Update validator version 08/05/24

- packages/specification/electronic-prescription-service-api.yaml
Marks dispensing api as in integration and production
> AEA-4043 Update the FHIR API Schema

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
- update validation-service-fhir-r4 to v1.0.172-alpha
> Update common libraries 03 June 2024

- .github/dependabot.yml
- change dependabot commit message so it passes checks
> Fix: [AEA-0000] - change dependabot commit message

- packages/specification/schemas/requests/dispensing/DispenseClaim.yaml
Added the missing status codes and descriptions to the claim section of the spec 
Pull requests should be named using the following format:
If the current release is x.y.z then
- a patch release increases z by 1
- a minor release increases y by 1
- a major release increases x by 1
> Docs: [AEA-4138] - Missing Claim MedicationDispense type status codes in spec

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
- packages/tool/azure/azure-build-pipeline.yml
- update to latest validator version
> Update: [AEA-0000] - update validator_version

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
- packages/tool/azure/azure-build-pipeline.yml
Package updates per Triage Rota.
> Upgrade: [AEA-0000] - Package updates

- .github/workflows/pull_request.yml
- .github/workflows/quality_checks.yml
- .github/workflows/release.yml
- Makefile
- packages/coordinator/package.json
- packages/tool/site/client/package.json
- sonar-project.properties
Adds Sonarcloud scan to repo workflow, and updates eslint config.
> Build: [AEA-4213] - Adds Sonarcloud Scan

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
- packages/tool/azure/azure-build-pipeline.yml
Updates validator to v1.0.184-alpha
> Upgrade: [AEA-0000] - Upgrades Common Libraries

- packages/specification/electronic-prescription-service-api.yaml
- packages/specification/schemas/components/MedicationRequest/CancelRequestMedicationRequest.yaml
- packages/specification/schemas/components/MedicationRequest/DispenseNotificationMedicationRequest.yaml
- packages/specification/schemas/components/MedicationRequest/MedicationRequest.yaml
- packages/specification/schemas/components/MedicationRequest/ReleaseMedicationRequest.yaml
- packages/specification/schemas/components/MessageHeader/MessageHeader.yaml
- packages/specification/schemas/components/Organization/DispenseNotificationOrganization.yaml
- packages/specification/schemas/components/Organization/Organization.yaml
- packages/specification/schemas/components/Organization/ReleaseOrganization.yaml
- packages/specification/schemas/components/Organization/ReturnOrganization.yaml
- packages/specification/schemas/components/Patient/Patient.yaml
- packages/specification/schemas/components/Practitioner/CancelRequestPractitioner.yaml
- packages/specification/schemas/components/Practitioner/CancelResponsePractitioner.yaml
- packages/specification/schemas/components/Practitioner/CreatePractitioner.yaml
- packages/specification/schemas/components/Practitioner/ReleaseResponsePractitioner.yaml
- packages/specification/schemas/components/PractitionerRole/CancelPractitionerRole.yaml
- packages/specification/schemas/components/PractitionerRole/CreatePractitionerRole.yaml
- packages/specification/schemas/components/PractitionerRole/TaskPractitionerRole.yaml
- packages/specification/schemas/components/_extensions/DMPrescriptionId.yaml
- packages/specification/schemas/components/_fragments/groupIdentifier.yaml
- packages/specification/schemas/components/_fragments/telecom.yaml
- packages/specification/schemas/requests/dispensing/DispenseNotification.yaml
Added all listed mandatory requirements from ticket into the spec
> Docs: [AEA-3930] - Updated mandatory fields for resources in spec

- sonar-project.properties
SonarCloud is reporting a really low test coverage. On inspection, it looks like our properties file is misconfigured, so let's fix that.
> Fix: [AEA-0000] - Fix SonarCloud Pipeline

- packages/specification/schemas/components/Patient/Patient.yaml
- packages/specification/schemas/components/Practitioner/CancelRequestPractitioner.yaml
- packages/specification/schemas/components/Practitioner/CreatePractitioner.yaml
Used the incorrect required tags on these names in the OAS in ticket AEA-3930, this is a PR to fix that and use the correct required (gives them a red asterisk rather than lists them underneath the parent item)
> Docs: [AEA-4372] - Updated to the correct required tags from AEA-3930

- .devcontainer/Dockerfile
- azure/azure-build-pipeline.yml
- packages/tool/azure/azure-build-pipeline.yml
New FHIR IG version in support of Welsh exemption and endorsement codes and NWSSP claiming.
> Update: [AEA-4357] - Updated FHIR validator

- examples/secondary-care/homecare/acute/nominated-pharmacy/clinical-practitioner/3-Convert-Response-Withdraw-200_OK.xml
- packages/coordinator/src/services/translation/request/agent-person.ts
- packages/coordinator/src/services/translation/request/withdraw/withdraw.ts
- packages/coordinator/tests/services/translation/request/agent-person.spec.ts
Updates translation of withdraw requests to include author ODS code
> Fix: [AEA-3517] - Translate the organisation resource from the FHIR withdraw request

- .github/scripts/delete_stacks.sh
- .github/workflows/delete_old_cloudformation_stacks.yml
> Fix: [AEA-4389] - delete old cname records

- sonar-project.properties
> Fix: [AEA-0000]  - fix sonar coverage

- .devcontainer/Dockerfile
- .github/workflows/sam_package_code.yml
- azure/azure-build-pipeline.yml
- packages/bdd-tests/features/createPrescription.feature
- packages/tool/azure/azure-build-pipeline.yml
- Revert "Fix: [AEA-4583] - use latest validator and fix tests (#2877)"
- use previous version of validator
> Fix: [AEA-4747] - switch to older validator version

- .github/workflows/create_int_release_notes.yml
- .github/workflows/create_prod_release_notes.yml
- .github/workflows/create_rc_int_release_notes.yml
- .github/workflows/delete_old_cloudformation_stacks.yml
- .github/workflows/mark_jira_released.yml
- .github/workflows/sam_release_code.yml
-  fix AWS session name in github actions
> Chore: [AEA-0000] - fix AWS session name in github actions

- packages/coordinator/package.json
- packages/tool/site/server/package.json
- enable source maps when running in docker
> Fix: [AEA-4860] - enable source maps when running in docker

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/sam_release_code.yml
- Makefile
- SAMtemplates/load_balancer/main.yaml
- SAMtemplates/main_template.yaml
- packages/coordinator/src/routes/health/get-status.ts
- packages/coordinator/src/services/communication/live-spine-client.ts
- packages/coordinator/src/services/communication/mtls-spine-client.ts
- packages/coordinator/src/services/communication/spine-client.ts
- packages/coordinator/src/utils/status.ts
- fix check to work out if should be using mtl spine cilent
- update dev spine servers
- use a docker image tag based on pull request and short commit sha for pull requests so it forces a new deployment on each push
- separate log groups for coordinator and validator docker services
- add agent param to serviceHealthCheck and pass it from mtls-spine-client so it can use the https agent with mutual tls
> Fix: [AEA-0000] - update AWS docker deployment

- packages/e2e-tests/services/update-prescriptions.ts
> Fix: [AEA-000] - fix signing pact tests

- packages/coordinator/src/services/communication/live-spine-client.ts
- packages/coordinator/tests/services/communication/spine-communication.spec.ts
- treat 500 polling response as a 202 response
> Fix: [AEA-4898] - treat 500 pollling response as 202

- packages/specification/schemas/components/_extensions/ODSOrganisationRelationships.yaml
Added additional info on ODS codes for BSA and NWSSP
> Docs: [AEA-4422] - Include the Reimbursement Authority ODS Codes in the Dispense Notification

- .github/workflows/release.yml
- fix running pact tests in main pipeline
> Fix: [AEA-0000] - fix pact tests in main pipeline

- packages/coordinator/src/services/translation/response/index.ts
- packages/coordinator/tests/services/translation/response/index.spec.ts
- log body when can not parse to fhir
> Fix: [AEA-0000] - Log unhandled spine response

- .github/workflows/run_pact_tests.yml
> Fix: [AEA-0000] - really fix pact tests

- .github/workflows/run_pact_tests.yml
- change order vars are evaluated in pact tests
> Fix: [AEA-0000] - fix pact tests (again)

- azure/templates/run_tests.yml
- create empty path for bdd results
> Fix: [AEA-0000] - create empty path for bdd results

- README.md
> Fix: [AEA-0000] - force version bump

- packages/coordinator/ecs-proxies-deploy-prod.yml
> Fix: [AEA-0000] - higher cpu for ecs in prod

- packages/coordinator/src/services/translation/response/spine-response-handler.ts
- packages/coordinator/src/utils/server-extensions.ts
- better logging on errors and warnings
> Fix: [AEA-0000] - better logging

- packages/coordinator/src/routes/debug/convert.ts
- packages/coordinator/src/routes/dispense/claim.ts
- packages/coordinator/src/routes/prescribe/prepare.ts
- packages/coordinator/src/routes/process.ts
- packages/coordinator/src/services/communication/tracker111/live.ts
- packages/coordinator/src/services/translation/common/response-bundles.ts
- packages/coordinator/src/services/translation/response/release/additional-instructions.ts
- packages/coordinator/src/services/translation/response/release/release-medication-request.ts
- packages/coordinator/src/services/translation/response/release/release-response.ts
- packages/coordinator/src/services/validation/bundle-validator.ts
- packages/coordinator/src/services/validation/claim-validator.ts
- packages/coordinator/tests/services/translation/request/practitioner.spec.ts
- packages/coordinator/tests/services/translation/response/release/additional-instructions.spec.ts
- packages/coordinator/tests/services/translation/response/release/release-medication-request.spec.ts
- packages/coordinator/tests/services/translation/response/release/release-response.spec.ts
- packages/coordinator/tests/services/translation/response/spine-response-handler.spec.ts
- packages/coordinator/tests/services/translation/reversibility.spec.ts
- packages/coordinator/tests/services/validation/bundle-validator.spec.ts
- packages/coordinator/tests/services/validation/claim-validator.spec.ts
- remove console logging in coordinator
> Fix: [AEA-4971] - remove console logging in coordinator

- .github/workflows/release.yml
- do not run proxygen qa tests so we can deploy to INT
> Fix: [AEA-000] - do not run proxygen qa tests

- .github/workflows/pull_request.yml
- Makefile
- SAMtemplates/main_template.yaml
- packages/coordinator/src/services/verification/certificate-revocation/verify.ts
- packages/coordinator/tests/services/verification/certificate-revocation.spec.ts
- do not proxy calls to CRL_DISTRIBUTION_DOMAIN when in eps hosted container
> Fix: [AEA-4970] - do not proxy calls to CRL_DISTRIBUTION_DOMAIN when in eps hosted container

- SAMtemplates/load_balancer/main.yaml
- SAMtemplates/main_template.yaml
> Fix: [AEA-0000] - fix enviroment in cloudformation

- .github/workflows/run_pact_tests.yml
- different artifact name for pact tests
> Fix: [AEA-0000] - different artifact name for pact tests

- .gitallowed
- packages/coordinator/ecs-proxies-deploy-prod.yml
- increase capacity for February month end
- update .gitallowed because of cdk branch
> Fix: [AEA-0000] - Increase capacity for February month end

- .github/scripts/delete_stacks.sh
- .github/workflows/pull_request.yml
- no mutual tls on pull requests
> Fix: [AEA-0000] - no mutual tls on pull requests

- packages/cdk/stacks/PrescribeDispenseStack.ts
- increase health check grace period
> Fix: [AEA-0000] - increase health check grace period

- .gitallowed
- packages/coordinator/src/services/verification/certificate-revocation/utils.ts
- packages/coordinator/src/services/verification/certificate-revocation/verify.ts
- packages/coordinator/src/utils/server-extensions.ts
- packages/coordinator/tests/Factory/dispenseProposalReturn.spec.ts
- packages/coordinator/tests/app.test.ts
- packages/coordinator/tests/services/translation/response/release/release-response.spec.ts
- packages/coordinator/tests/services/verification/signature-verification.spec.ts
- proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml
- proxies/live/apiproxy/policies/FlowCallout.LogToSplunkRequestContentBody.xml
- proxies/live/apiproxy/proxies/default.xml
- do not log request body in apigee
- log request body for error/warnings in container for APIM deployment 
- handle no sub ca list
- increase timeout on some unit tests as they can take a longer time locally
> Fix: [AEA-0000] - do not log body in apigee

- package-lock.json
- packages/coordinator/package.json
- packages/e2e-tests/package.json
- packages/models/package.json
- packages/tool/site/server/package.json
> Fix: [AEA-0000] - remove unneeded types

- scripts/run_regression_tests.py
- latest regression test pack version
> Fix: [AEA-0000] - latest regression test pack version

- packages/specification/fhir-dispensing.yaml
- packages/specification/fhir-prescribing.yaml
- tweak specs to force re-publish
> Chore: [AEA-0000] - tweak specs to force publish

- packages/tool/site/server/src/services/session.ts
Builds are failing because of a typing error. I'm leary to make a code change to such old code, and this file is riddled with eslint ignore comments, so I'm happier with just adding one to this line. It allows the build to go through, and tests pass locally, so I think this is fine.
> Fix: [AEA-0000] - Add an ignore statement

- .github/scripts/deploy_api.sh
- packages/specification/fhir-dispensing.yaml
- packages/specification/fhir-prescribing.yaml
> Fix: [AEA-0000] - enable monitoring

- package-lock.json
- packages/tool/site/Dockerfile
- packages/tool/site/client/index.html
- packages/tool/site/client/package.json
- packages/tool/site/client/static/.gitignore
- add nhs-uk frontend as dependency
- copy nhs-uk stylesheet to epsat container
> Fix: [AEA-0000]- add nhs-uk frontend sytlesheet to epsat

- scripts/run_regression_tests.py
- bump regression test version to include changes to add apigee product
> Fix: [AEA-0000] - bump regression test version

- .github/workflows/release.yml
- packages/cdk/stacks/PrescribeDispenseStack.ts
- scale claims service at month end between 07:00 and 01:00
> Fix:[AEA-5319] - scale claims

- scripts/run_regression_tests.py
- use latest regression test tag
> Fix: [AEA-0000] - use latest regression test tag

- azure/templates/run_tests.yml
- skip regression tests in sandbox
> Fix: [AEA-0000] - skip sandbox regression

- packages/cdk/stacks/PrescribeDispenseStack.ts
- increase idle timeout
- set ssl policy
> Fix: [AEA-5440] - increase idle timeout

- .devcontainer/Dockerfile
- .github/workflows/cdk_package_code.yml
- azure/azure-build-pipeline.yml
- packages/tool/azure/azure-build-pipeline.yml
> Fix: [AEA-0000] - update validator version

- .github/workflows/pr-link.yml
- use commit sha for comment on pr github action
> Fix: [AEA-0000] - use commit sha for comment on pr

- package-lock.json
- packages/bdd-tests/package.json
- packages/coordinator/package.json
- packages/e2e-tests/package.json
- packages/models/package.json
- packages/tool/site/client/package.json
- packages/tool/site/server/package.json
> Upgrade: [AEA-0000] - bump axios

- packages/specification/electronic-prescription-service-api.yaml
- packages/specification/fhir-dispensing.yaml
- packages/specification/fhir-prescribing.yaml
🎫 [AEA-5095](https://nhsd-jira.digital.nhs.uk/browse/AEA-5095) Update OAS to state NHSD-Session-URID is mandatory
This pull request updates OAS to state `NHSD-Session-URID` is mandatory.
> Docs: [AEA-5095] - Update OAS to state NHSD-Session-URID is mandatory

- .github/scripts/deploy_api.sh
- fix sandbox pr deployment as it was not getting pull request id correctly
> Fix: [AEA-0000] - fix sandbox pr deployment
