NHSDigital/electronic-prescription-service-api

scripts/identify_external_release_changes.py

- Compare int with internal-dev instead of internal-qa.
- Only log out tagged commits (results in one line per change even if someone doesn't squash commits).

Update release changes script.

---

coordinator/src/services/translation/response/patient.ts
coordinator/src/services/translation/response/release/release-response.ts

- Use the new textual code instead of the old numeric one.
- Exclude the extension entirely in the context of CommunicationRequest.recipient.

AEA-1779: Fix NHS number verification status in release response.

---

manifest_template.yml

https://nhsd-jira.digital.nhs.uk/browse/APM-2869
Associating the relevant products that can use mock-oauth with the corrisponding identity-service proxy

APM-2869 Associate products with oauth mock service

---

README.md

We're now on Node 16.14.x
nvm also has a newer version, so we can upgrade to the latest

Update nvm and Node versions in setup docs

---

README.md
coordinator/src/services/validation/bundle-validator.ts
coordinator/tests/services/validation/bundle-validator.spec.ts
models/errors/validation-errors.ts

AC 1.1
WHEN a GMP code is the only professional identifier that is provided for a prescriber,
THEN the FHIR Facade API needs to reject this
AND request that a more suitable identifier, e.g. a GMC Reference Number, is provided for the creation of a prescription

AEA-2527 Population of Prescriber Codes

---

coordinator/src/services/validation/bundle-validator.ts
coordinator/tests/services/validation/bundle-validator.spec.ts
models/errors/validation-errors.ts

Chat with Ameya and Chris T, misunderstood that SDS User Identifier and DIN don't come under Professional Identifiers, so new expected behaviour is if there is a GMP under Practitioner.Identifier (regardless of whether there's other identifiers in there) then it should still throw the error to recommend a more suitable identifier.

AEA-2527 Population Prescriber Update

---

coordinator/src/services/translation/response/organization.ts
coordinator/tests/services/translation/response/cancellation/cancellation-response.spec.ts
coordinator/tests/services/translation/response/organization.spec.ts
coordinator/tests/services/translation/response/release/release-response.spec.ts

createOrganization function now creates Organisation with the type field not populated by default. The createOrganization method is used to populate organisation for the cancel response and release response. Tests updated appropriately.

Aea 2560 remove organisation type in cancel response

---

coordinator/src/services/translation/request/practitioner.ts
coordinator/tests/services/translation/request/practitioner.spec.ts

Used to have this functionality, got lost over the past 2 years, now adding it back

AEA-2714 Removal logic for leading C's on GMC codes

---

proxies/live/apiproxy/policies/Quota.xml
proxies/live/apiproxy/policies/SpikeArrest.xml

Just a change to Quota.xml and SpikeArrest.xml which can act as a default to the rate limiting set in the manifest_template.yml for un-authenticated access.

Ref rate limits

---

tests/e2e/pact/broker/verify.ts

Tests are failing because they require the prescriptions used to be present in INT and to have a valid signature.
Disabling the tests for PTL in order to unblock releases to INT and QA, as they will be addressed with future work on key fields comparison (AEA-2645).

AEA-2710 Disable verify-signature Pact tests for PTL envs

---

coordinator/tests/services/translation/request/prescription.spec.ts
examples/errors/2-Prepare-Request-400_Invalid_Course_of_Therapy_mixed.json
examples/errors/2-Process-Request-Send-400_Invalid_Course_of_Therapy_mixed.json
examples/primary-care/acute-and-repeat-prescribing/1-Prepare-Request-200_OK.json
examples/primary-care/acute-and-repeat-prescribing/1-Process-Request-Send-200_OK.json
examples/primary-care/repeat-dispensing/nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/medication-list/din/1-Convert-Response-Send-200_OK.xml
examples/primary-care/repeat-dispensing/nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/medication-list/din/1-Prepare-Request-200_OK.json
examples/primary-care/repeat-dispensing/nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/medication-list/din/1-Process-Request-Send-200_OK.json
examples/primary-care/repeat-dispensing/nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/medication-list/spurious-code/1-Convert-Response-Send-200_OK.xml
examples/primary-care/repeat-dispensing/nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/medication-list/spurious-code/1-Prepare-Request-200_OK.json
examples/primary-care/repeat-dispensing/nominated-pharmacy/medical-prescriber/author/gmc/responsible-party/medication-list/spurious-code/1-Process-Request-Send-200_OK.json
examples/primary-care/repeat-prescribing/1-Convert-Response-Send-200_OK.xml
examples/primary-care/repeat-prescribing/1-Prepare-Request-200_OK.json
examples/primary-care/repeat-prescribing/1-Process-Request-Send-200_OK.json
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/non-prescriber-endorsed/1-Convert-Response-Send-200_OK.xml
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/non-prescriber-endorsed/1-Prepare-Request-200_OK.json
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/non-prescriber-endorsed/1-Process-Request-Send-200_OK.json
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/prescriber-endorsed/1-Convert-Response-Send-200_OK.xml
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/prescriber-endorsed/1-Prepare-Request-200_OK.json
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/multiple-medication-requests/prescriber-endorsed/1-Process-Request-Send-200_OK.json
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/single-medication-request/1-Convert-Response-Send-200_OK.xml
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/single-medication-request/1-Prepare-Request-200_OK.json
examples/secondary-care/community/repeat-dispensing/nominated-pharmacy/clinical-practitioner/single-medication-request/1-Process-Request-Send-200_OK.json
specification/schemas/MedicationRequest/extensions/MedicationRepeatInformation.yaml

The date for authorisationExpiryDate is now a value in the past, so tests started failing.
A search and replace is the quick solution and fixes the issue for a couple of years.

AEA-2644 Set tests authorisationExpiryDate to a date in the future

---

packages/coordinator/jest.config.js
packages/coordinator/src/routes/dispense/claim.ts
packages/coordinator/src/routes/dispense/release.ts
packages/coordinator/src/routes/dispense/task.ts
packages/coordinator/src/routes/dispense/verify-signature.ts
packages/coordinator/src/routes/polling.ts
packages/coordinator/src/routes/process.ts
packages/coordinator/src/routes/util.ts
packages/coordinator/src/services/translation/request/return/return-factory.ts
packages/coordinator/src/services/translation/response/index.ts
packages/coordinator/src/services/translation/response/release/release-response.ts
packages/coordinator/src/services/translation/response/spine-response-handler.ts
packages/coordinator/src/services/verification/certificate-revocation/utils.ts
packages/coordinator/src/services/verification/signature-verification.ts
packages/coordinator/tests/routes/util.spec.ts
packages/coordinator/tests/services/translation/response/index.spec.ts
packages/coordinator/tests/services/translation/response/release/release-response.spec.ts
packages/coordinator/tests/services/translation/response/spine-response-handler.spec.ts
packages/coordinator/tests/services/verification/certificate-revocation.spec.ts
packages/coordinator/tests/services/verification/signature-verification.spec.ts

When we verify the certificate on a signature, we need to fetch the partitioned CRL, so functions needed to be converted to async.
- Made src and test functions async
- Made number of jest workers fixed to fix random test failures

AEA-2650 Refactor Spine response translation to async

---

.devcontainer/Dockerfile
azure/azure-build-pipeline.yml

Update FHIR validator verson in support of Welsh Prescription Type Codes
- :exclamation: Breaking Change
- :sparkles: New Feature
Welsh prescription type codes were added to the Spine under https://nhsd-jira.digital.nhs.uk/browse/AEA-2769

AEA-3603 Update FHIR validator verson in support of Welsh Prescription Type Codes

---

.github/dependabot.yml
.github/workflows/continuous-integration.yml

- Use https://github.com/ncipollo/release-action to create a release as actions/create-release@v1 is not supported
- Use correct config for dependabot python

AEA-3556 use support create release

---

examples/spec/dispensing/withdraw/acute-primary-example-req.json
examples/spec/dispensing/withdraw/eRD-primary-example-req.json
examples/spec/dispensing/withdraw/repeat-primary-example-req.json

- Documentation change.
-  `status` field can only accept `in-progress` or `rejected` for _Withdraw - Despensing_ 
- Edits the value of `status` in the requests of _acute_, _repeat_ and _eRD_ within _Withdraw - Despensing_ from `cancelled` to `in-progress`.
- This change should result in *200* instead of *400*.

AEA-3666: OAS Dispense - Withdraw page Try button returns 400 Bad Request

---

packages/specification/electronic-prescription-service-api.yaml

🎫 Jira Reference: [AEA-3681](https://nhsd-jira.digital.nhs.uk/browse/AEA-3681)
The prescription search tracking information is removed from the API catalogue.
- :exclamation: Breaking Change
The prescription search tracking information needs to be removed from the API catalogue here: [https://digital.nhs.uk/developer/api-catalogue/electronic-prescription-service-fhir#get-/FHIR/R4/Task, ](https://digital.nhs.uk/developer/api-catalogue/electronic-prescription-service-fhir#get-/FHIR/R4/Task)in light of the development of the new Clinical Prescriptions Tracker.

AEA-3681 Remove prescription search tracking information from API catalogue

---

packages/specification/schemas/components/MedicationDispense/MedicationDispense.yaml

Ticket https://nhsd-jira.digital.nhs.uk/browse/AEA-3691
In our Dispensing schema we mention in the dispense notification section about 'Not Dispensed' prescriptions. This though doesn't give suppliers all the information required to help with onboarding to our API. 
Within the `statusReasonCodeableConcept` field in the `MedicationDispense` edit the `code` and `display` fields to contain their respective enums:
Code	Display
0001	Not required as instructed by the patient	
0002	Clinically unsuitable	
0003	Owings note issued to patient	
0004	Prescription cancellation	
0005	Prescription cancellation due to death	
0006	Illegal NHS prescription	
0007	Prescribed out of scope item	
0008	Item or prescription expired	
0009	Not allowed on FP10	
0010	Patient did not collect medication …

AEA- 3691 Update Reason Codes in the schema for 'Not Dispensed' in the Dispense Notification

---

examples/spec/dispensing/dispense-notification/acute-primary-example-01-req.json
examples/spec/dispensing/dispense-notification/acute-primary-example-02-req.json
examples/spec/dispensing/dispense-notification/acute-primary-example-03-req.json
examples/spec/dispensing/dispense-notification/acute-primary-example-04-req.json
examples/spec/dispensing/dispense-notification/eRD-primary-example-req.json
examples/spec/dispensing/dispense-notification/repeat-primary-example-req.json

:ticket: [AEA-3665](https://nhsd-jira.digital.nhs.uk/browse/AEA-3665)
OAS Dispense - Notification page Try button returns 400 Bad Request
The Try button on the Dispense - Notification page is returning a 400 Bad Request.
I have attached the full json response.
[BadRequest.Json](https://nhsd-jira.digital.nhs.uk/secure/attachment/627040/627040_BadRequest.Json)
"diagnostics": "Expected all MedicationDispenses to have the same value for whenHandedOver.
"expression": ["Bundle.entry.resource.ofType(MedicationDispense).whenHandedOver"
[Electronic Prescription Service - FHIR API - NHS Digital](https://digital.nhs.uk/developer/api-catalogue/electronic-prescription-service-fhir#post-/FHIR/R4/$process-message-dispense-n …

AEA-3665 OAS Dispense - Notification page Try button returns 400 Bad Request 

---

packages/specification/electronic-prescription-service-api.yaml

This ticket is to update the 4XX in the Response section, of the Download prescriptions - Dispensing endpoint in the OAS
https://nhsd-jira.digital.nhs.uk/browse/AEA-3320
-   /FHIR/R4/Task/$release
The descriptions for the error codes have been updated as shown below:
400 	: Another dispenser has previously released this prescription. Details of the prescription will be in OperationOutcome.contained.Organization 
400 	: The prescription ID specified in the parameters requested (group-identifier) did not exist.

AEA-3320 Update Error Response Table in the OAS for the Release Endpoint

---

packages/tool/e2e-tests/live.test.ts

- use new headless mode for epsat e2e tests - https://www.selenium.dev/blog/2023/headless-is-going-away/

AEA-3781 use new headless mode for epsat tests

---

packages/specification/electronic-prescription-service-api.yaml

https://nhsd-jira.digital.nhs.uk/browse/AEA-3883
Correct grammar in error message for OAS.
Error message was edited.

AEA-3883 - Typo in OAS ( "Encode prescription data so it's ready to sign - Prescribing" )

---

examples/spec/dispensing/dispense-notification/acute-primary-example-01-req.json
examples/spec/dispensing/dispense-notification/acute-primary-example-02-req.json
examples/spec/dispensing/dispense-notification/acute-primary-example-03-req.json
examples/spec/dispensing/dispense-notification/acute-primary-example-04-req.json
examples/spec/dispensing/dispense-notification/eRD-primary-example-req.json
examples/spec/dispensing/dispense-notification/repeat-primary-example-req.json
packages/specification/schemas/components/MedicationDispense/MedicationDispense.yaml

🎫 [AEA-3871](https://nhsd-jira.digital.nhs.uk/browse/AEA-3871) Update examples and the schema to remove RunningTotal field
A decision was made, via [Decision Log D026](https://nhsd-confluence.digital.nhs.uk/display/APIMC/D026%3A+Running+total+is+missing+from+repeat+dispensing+HL7v3+dispense+claim+translations), that we wouldn't support RunningTotal in FHIR as it's not used downstream anywhere / isn't mapped to HL7v3. Update examples and the schema to remove RunningTotal field.

AEA-3871 Update examples and the schema to remove RunningTotal field

---

packages/coordinator/src/services/validation/claim-validator.ts
packages/coordinator/tests/services/validation/claim-validator.spec.ts
packages/models/errors/validation-errors.ts

Reverts AEA-4528 to enable reimbursement authority validation

New: [AEA-4358] - Enable Validate Reimbursement Authority

---

packages/specification/schemas/components/_extensions/DMResponsiblePractitioner.yaml

Updated to requester and responsible practitioner
Where it says 'Author' this has been changed to 'Requester' and where it says 'Responsible Party' this has been changed to Responsible Practitioner. 
Pull requests should be named using the following format:
```text
Docs: [AEA-4426] - OAS Update - Update Author, Authored and Responsible Party in the 'Mark a prescription as dispensed
```
- `Docs` - changes to documentation only. (Patch release)

Docs: [AEA-4426] - OAS Update - Update Author, Authored and Responsible Party in the 'Mark a prescription as dispensed

---

packages/coordinator/src/utils/headers.ts
packages/coordinator/tests/utils/headers.spec.ts

- fix sandbox deployment by having a default sandbox party key

Fix: [AEA-0000] - fix sandbox deployments

---

azure/azure-release-pipeline.yml

- do not require asid in qa for apim deploymentss

Fix: [AEA-0000] - do not require asid in qa apim deployment

---

.gitallowed
package-lock.json
packages/coordinator/package.json
packages/coordinator/src/server.ts
packages/coordinator/src/utils/server-extensions.ts
packages/coordinator/tests/app.test.ts
packages/coordinator/tests/logging/incomingPayloads.spec.ts

- log payload on error or warning response
- use a different port for hapi tests to avoid clashes

Fix: [AEA-5057] - log payload on error or warning response

---

.gitallowed
packages/coordinator/src/services/verification/certificate-revocation/utils.ts
packages/coordinator/src/services/verification/certificate-revocation/verify.ts
packages/coordinator/src/services/verification/common.ts
packages/coordinator/src/services/verification/signature-verification.ts
packages/coordinator/tests/services/verification/certificate-revocation.spec.ts
packages/coordinator/tests/services/verification/signature-verification.spec.ts

- do not allow prescriptions with multiple certificates to be released
- only use crypto to extract certificate

Fix: [AEA-5132] - reject multiple certificates

---

packages/coordinator/src/utils/headers.ts

- always use default asid/party key in PTL

Fix: [AEA-5172] - always use default asid/party key in PTL

---

packages/coordinator/src/services/communication/common.ts
packages/coordinator/tests/services/communication/spine-communication.spec.ts

- use retry-after in response to decide how long to wait before polling again

Fix: [AEA-5269] - use retry-after in response to decide how long before polling

---

packages/cdk/resources/LogGroups.ts
packages/coordinator/src/services/communication/common.ts
packages/coordinator/tests/services/communication/spine-communication.spec.ts

- send claims validator logs to splunk
- correct delay between polling

Fix: [AEA-0000] - use fixed polling delay and send claims validator logs to splunk

---

examples/primary-care/acute/nominated-pharmacy/medical-prescriber/1-Process-Request-Send-200_OK.json
examples/primary-care/acute/nominated-pharmacy/medical-prescriber/3-Process-Request-Multiple-DosageInstructions-Send_200_OK.json
examples/primary-care/acute/nominated-pharmacy/responsible-party-org/3-Process-Request-Send-200_OK.json
examples/primary-care/repeat-prescribing/1-Process-Request-Send-200_OK.json
examples/spec/prescribing/prescription-order/eRD-primary-example-req.json

🎫 [AEA-5291](https://nhsd-jira.digital.nhs.uk/browse/AEA-5291) Update Provenance target to reference MedicationRequests
This pull request updates `Provenance.target` to reference `MedicationRequest` resources instead of the `Bundle` ID.

Docs: [AEA-5291] - Update Provenance target to reference MedicationRequests
